### ISSUE TITLE
No Module named pyphp.scope

### ISSUE THREAD

**Issue by hppavilion1** [g-i-o-/pyphp#2]
Traceback (most recent call last):
  File "C:\Users\Nathan\Desktop\Programming\Python\Web\Servers\HTTP-WalServeUs\WalServeUs.py", line 4
    from plugins import *
  File "C:\Users\Nathan\Desktop\Programming\Python\Web\Servers\HTTP-WalServeUs\plugins\php.py", line 1
    import pyphp.executer
  File "C:\Users\Nathan\Desktop\Programming\Python\Web\Servers\HTTP-WalServeUs\plugins\pyphp\executer.py", line 3
    import phpbuiltins
  File "C:\Users\Nathan\Desktop\Programming\Python\Web\Servers\HTTP-WalServeUs\plugins\pyphp\phpbuiltins\__init__.py", line 5
    import pyphp.scope as scope
ImportError: No module named pyphp.scope

Sorry to have to create another issue for this. Was this developed on Unix/Mac? That might explain the problem, as I am on Windows (for now)

**Comment by g-i-o-** [comment]
It seems you're having problems importing the `pyphp` module from within the builtins directory. This can only if the system cannot find it using the paths in `sys.path`.

How are you importing `pyphp`? It looks like it is basically just copied over the `plugins` directory.
In that case, you need to make sure that the `pyphp` module can be found from the paths in `sys.path`.  You could, for example add a few lines into the `plugins/__init__.py` that does such a thing:

```python
import sys
import os.path

pluginlibs = os.path.dirname(os.path.abspath(__filename__))
sys.path.append(pluginlibs)
```

Another thing you could try is installing the module on your system with the `setup.py` script.

**Comment by g-i-o-** [comment]
I just realized that you wrote to me on issue #1 after this one. Were you able to fix it then?

**Comment by hppavilion1** [comment]
No, that was just another issue.

**Comment by ghost** [comment]
OK, I added that code and it works. I don't like having to modify the init file, but I suppose I had to do it :/. Thanks for the help! My server now supports PHP. This was a huge help. Everyone on my team is excited. That is to say two people. Thanks!

**Comment by g-i-o-** [comment]
Great, you're welcome. I hope to be adding more functionality to the php that's supported, but, well this is a one man team in here :-).

**Comment by ghost** [comment]
@g-i-o I'd help, but I frankly have no clue how your code works :P
Have you set it up in a way that one would easily be able to implement new functions? If so, I _might_ be able to help you out.
